### ISSUE TITLE
bug: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback

### ISSUE THREAD

**Issue by geekyouth** [casdoor/wordpress-casdoor-plugin#14]
You:
 PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, non-static method Casdoor::custom_login() cannot be called statically in /var/www/html/wp-includes/class-wp-hook.php:308\nStack trace:\n#0 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)\n#1 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#2 /var/www/html/wp-settings.php(623): do_action('init')\n#3 /var/www/html/wp-config.php(133): require_once('/var/www/html/w...')\n#4 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')\n#5 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...')\n#6 /var/www/html/wp-admin/plugins.php(10): require_once('/var/www/html/w...')\n#7 {main}\n  thrown in /var/www/html/wp-includes/class-wp-hook.php on line 308, referer: http://127.0.0.1/wp-admin/plugins.php?plugin_status=all&paged=1&s   用中文回复

ChatGPT:
这个PHP致命错误是由于在`/var/www/html/wp-includes/class-wp-hook.php`的第308行，`call_user_func_array()`函数试图静态调用一个非静态方法`Casdoor::custom_login()`。这是不允许的，因此导致了错误。

要解决这个问题，您可以尝试以下步骤：

1. 打开引发错误的插件或主题中的`Casdoor`类定义的文件。

2. 在`Casdoor`类中，找到`custom_login()`方法定义。

3. 将该方法声明为静态方法，即在`function`关键字前添加`static`关键字，如下所示：

   ```php
   public static function custom_login() {
       // 方法实现
   }
   ```

4. 保存更改并重新加载您的WordPress页面。

请注意，这只是一个快速修复。更好的解决方案可能是查看插件或主题的文档或联系开发人员，以获取更多关于如何正确使用`Casdoor::custom_login()`方法的信息。根据插件或主题的设计，可能需要实例化`Casdoor`类并使用对象调用`custom_login()`方法，而不是静态调用。

**Comment by hsluoyz** [comment]
@geekyouth hi, can you make a PR to add: https://github.com/geekyouth/wordpress-casdoor-plugin/commit/56292d4e8dcd36ed936c530a78369228c1cf3851 ?

**Comment by geekyouth** [comment]
> @geekyouth hi, can you make a PR to add: [geekyouth@56292d4](https://github.com/geekyouth/wordpress-casdoor-plugin/commit/56292d4e8dcd36ed936c530a78369228c1cf3851) ?

已提交 PR 等待审核中
