### ISSUE TITLE
The wordpress-casdoor-plugin not work on wordpress（ver 6.4.1）

### ISSUE THREAD

**Issue by jyxenlink** [casdoor/wordpress-casdoor-plugin#16]
When I finished installing WordPress (version 6.4.1) and uploading this plugin, the site prompted an error:

“Fatal error: Cannot redeclare get_options() (previously declared in D:\wwwroot\test.xhsyxx.cn\wp-includes\option.php:357) in D:\wwwroot\test.xhsyxx.cn\wp-content\plugins\casdoor-plugin\includes\functions.php on line 17”

please troubleshoot and fix it

**Comment by SkylarLeo** [comment]
Yes，I also encountered this problem

**Comment by hsluoyz** [comment]
@jyxenlink @SkylarLeo fixed by: https://github.com/casdoor/wordpress-casdoor-plugin/commit/e80add0a20cfbfe076d043187e026e11dc5476a9
